In [4]:
import numpy as np
A= np.array([[1,2,3,5],
            [10,20,40,60],
            [21,40,20,10]])


>          np.sum(a)          ------>元素求和  
>          np.sum(a, axis=0) ------->列求和
>          np.sum(a, axis=1) ------->行求和

In [6]:
cal1 = A.sum()
cal2 = A.sum(axis=0)
print(cal2)

[32 62 63 75]


In [10]:
percentage = A/cal2.reshape(1,4)
print(percentage)

[[0.03125    0.03225806 0.04761905 0.06666667]
 [0.3125     0.32258065 0.63492063 0.8       ]
 [0.65625    0.64516129 0.31746032 0.13333333]]


> .reshape(1,4)可以不写，但是为了稳定性我们还是加上,因为numpy丰富的接口同时也带来了一定的风险,一定要分清楚数组和矩阵的语法区别

In [12]:
a = np.random.randn(5)
print(a)
print(a.shape)

[ 0.83758596 -0.52087424 -0.7286271   1.08595922 -0.13301474]
(5,)


可以看到a的shape为(5,),此时我们打印a.T和np.dot(a,a.T),发现与意料不符合,理应是个5x5的矩阵才对

In [14]:
print(a.T)
print(np.dot(a,a.T))

[ 0.83758596 -0.52087424 -0.7286271   1.08595922 -0.13301474]
2.7007579966623725


为了规范我们应该让a为矩阵形式才好

In [ ]:
a = np.random.randn(5,1) #5x1的列向量
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

实际上`a = np.random.randn(5)`是创建了一个rank(秩)为1的数组,为了防止这种不规范的行为我们可以使用reshape方法:

In [20]:
assert (a.shape==(5,1)),a.reshape((5,1))

> 总之:1.不要使用rank=1的数组，2.自由使用assert检查维数和矩阵规格,3.用reshape即时调整